server:
  port: 8082

spring:
  application:
    name: order-service
  profiles:
    active: rabbitmq
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Configuración personalizada de Seguridad
jwt:
  secret: "MiClaveSecretaSuperSeguraQueDebeCoincidirConLaDeAuthService123456"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.uade.arquitectura: DEBUG
